spec:
  replicas: 2
  template:
    spec:
      containers:
      - livenessProbe:
          httpGet:
            path: "/"
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: "/"
            port: 8080
          initialDelaySeconds: 10